name: Testing

on: [push, pull_request]

jobs:
  build:

    strategy:
      max-parallel: 20
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.os }}

    env:
      PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
      MPLBACKEND: "Agg"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
#    - name: Install dependencies
#    - uses: conda-incubator/setup-miniconda@v2
#      with:
#        python-version: ${{ matrix.python-version }}
#        environment-file: test_env/test_env.yaml
#
#        channels: conda-forge,defaults
#
#        activate-environment: test
#        auto-update-conda: false
#        auto-activate-base: false
#        show-channel-urls: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        conda install --quiet -c conda-forge --file requirements.txt
        conda install --quiet -c conda-forge parmed openmm openff-toolkit
        pip install pymatgen
        pip install --quiet -r requirements-ci.txt
        pip install -e .
    - name: pytest
      run: |
        pytest pymatgen
